name: Publish API Client

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Set Tag
        id: set_tag
        run: |
          echo "tag=$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v//p')" >> $GITHUB_OUTPUT

  publish-api-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Update version in api-client/package.json
        working-directory: ./api-client
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          pnpm version $VERSION --no-git-tag-version

      - name: Publish
        working-directory: ./api-client
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  publish-docker:
    uses: ./.github/workflows/publish-console-docker.yml
    needs:
      - prepare
    with:
      tag: ${{ needs.prepare.outputs.tag }}
