name: publish-docker
run-name: Publish Docker Images
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
        default: ''
permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 22

      - name: Installing Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -ws

      - name: Build
        run: npm run build -ws

      - name: Publish Image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-bridge-console
          dockerfile: ./console/Dockerfile
          context: ./console
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
